### ISSUE TITLE
Sound remains blocked even after uninstalling

### ISSUE THREAD

**Issue by Andr0oS** [korti11/bettermuffling#16] opened 2020-08-28 04:47 UTC
1.16.1, most up-to-date version of the mod, effects of the muffler seem to remain even after deleting the item, and somehow even after uninstalling the mod.

**Comment by korti11** [comment] 2020-08-31 10:56
I'm sorry to hear that.
To take a look at this I would like to know on which Forge version you are playing and what other mods you are using in this Minecraft instance.

**Comment by Andr0oS** [comment] 2020-09-01 09:02
Probably the easiest way to get a modlist and forge version is just to link to the curseforge page of All the Mods 6, since that's the pack I'm in. I've reloaded your mod to try and see if there's any way to fix it, but I've had no luck. The version of the pack I've been on is 0.29, and the forge version I've been using is  32.0.108
https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/relations/dependencies

**Comment by korti11** [comment] 2020-10-11 10:54
After some testing I could not reproduce this behavior so I will close this issue for now.
If someone else gets this behavior feel free to comment and I will open this again for further investigation.

**Closed as completed by korti11** 2020-10-11 10:54 UTC
